# Generated by Django 4.2.4 on 2023-10-13 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS content;",
            reverse_sql="DROP SCHEMA IF EXISTS content;",
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Transport", "Transport"),
                            ("Real Estate", "Real Estate"),
                            ("Job", "Job"),
                            ("Service", "Service"),
                            ("Personal Usage", "Personal Stuff"),
                            ("For Home", "For Home"),
                            ("Electronics", "Electronics"),
                            ("Hobby and Leisure", "Hobby and Leisure"),
                            ("Pets", "Pets"),
                            (
                                "Business and Business Equipment",
                                "Business and Business Equipment",
                            ),
                        ],
                        max_length=31,
                    ),
                ),
            ],
            options={
                "db_table": 'content"."category',
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Cars", "Cars"),
                            ("Motorcycles", "Motorcycles"),
                            ("Trucks", "Trucks and Special Equipment"),
                            ("Water", "Water"),
                            ("Parts and Accessories", "Parts and Accessories"),
                            ("Overseas Properties", "Overseas Estate"),
                            ("Apartments", "Apartments"),
                            ("Rooms", "Rooms"),
                            ("Houses", "Houses"),
                            ("Parking", "Parking"),
                            ("Commercial Properties", "Commercial Properties"),
                            ("Vacancies", "Vacancies"),
                            ("IT/Telecom", "IT/Telecom"),
                            ("Business Services", "Business Services"),
                            ("Tutoring", "Tutoring"),
                            ("Building", "Building"),
                            ("Other", "Other"),
                            ("Clothes and Footwear", "Clothes and Footwear"),
                            (
                                "Clothes and Footwear for Kids",
                                "Clothes and Footwear for Kids",
                            ),
                            ("Baby Products and Toys", "Baby Products and Toys"),
                            ("Accessories", "Accessories"),
                            ("Health and Beauty", "Health and Beauty"),
                            ("Household Equipment", "Household Equipment"),
                            ("Furniture and Interior", "Furniture and Interior"),
                            (
                                "Dishes and Kitchen Equipment",
                                "Dishes and Kitchen Equipment",
                            ),
                            ("Groceries", "Groceries"),
                            ("Maintenance and Building", "Maintenance and Building"),
                            ("Plants", "Plants"),
                            ("Audio and Video", "Audio and Video"),
                            ("Videogaming", "Videogaming"),
                            ("Personal Computers", "Personal Computers"),
                            ("Laptops", "Laptops"),
                            ("Phones", "Phones"),
                            ("Other", "Other"),
                            ("Tickets", "Tickets"),
                            ("Bikes", "Bikes"),
                            ("Books and Magazines", "Books and Magazines"),
                            ("Collecting", "Collecting"),
                            ("Hunting and Fishing", "Hunting and Fishing"),
                            ("Sports and Leisure", "Sports and Leisure"),
                            ("Dogs", "Dogs"),
                            ("Cats", "Cats"),
                            ("Birds", "Birds"),
                            ("Fish", "Fish"),
                            ("Other Pets", "Other Pets"),
                            ("Pest Products", "Pest Products"),
                            ("Business for Sale", "Business for Sale"),
                            ("Business equipment", "Business equipment"),
                        ],
                        max_length=30,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "db_table": 'content"."subcategory',
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "description",
                    models.CharField(max_length=1500, verbose_name="Description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Price"
                    ),
                ),
                ("city", models.CharField(max_length=200, verbose_name="City")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aggregator.category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aggregator.subcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": 'content"."post',
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="photo/%Y/%m/%d/"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aggregator.post",
                    ),
                ),
            ],
            options={
                "db_table": 'content"."media',
            },
        ),
    ]
