# Generated by Django 4.1.3 on 2022-12-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="name",
            new_name="title",
        ),
    ]
