# Generated by Django 4.1.3 on 2022-12-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0002_rename_name_post_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="category",
        ),
    ]
