# Generated by Django 4.1.4 on 2022-12-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0003_remove_subcategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photo/%Y/%m/%d/"),
        ),
    ]
