version: "3.8"

volumes:
  postgres_data: {}
  static_data: {}

services:
  psql:
    image: postgres:14
    env_file:
      - ./.envs/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django-craigav:
    