# Generated by Django 4.2.4 on 2023-09-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
